<?php return array (
  'site_title' => 'Elmston',
  'base_color' => '00006b',
  'time_zone' => 'UTC',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'theme' => 'deepblue',
  'fraction_number' => 0,
  'paginate' => 20,
  'email_verification' => 0,
  'email_notification' => 1,
  'sms_verification' => 0,
  'sms_notification' => 1,
  'investment_commission' => 1,
  'deposit_commission' => 1,
  'sender_email' => 'help@elmston.co',
  'sender_email_name' => 'We are Elmston',
  'email_description' => '"<p style=\\"text-align: center; \\"><img src=\\"https:\\/\\/elmston.co\\/assets\\/uploads\\/content\\/Mail-header.jpg\\" style=\\"width: 969px;\\"><br><\\/p><p><br><\\/p><p>Querido [[name]],<br>[[message]].<br><\\/p><p><br><span style=\\"font-size: 13px;\\">\\u2022\\u2022\\u2022<\\/span><\\/p><p><b style=\\"font-size: 1rem;\\">Informaci\\u00f3n importante sobre seguridad y privacidad<\\/b><\\/p><p>Su ID de usuario y contrase\\u00f1a de ELMSTONOnline, son privados y nunca deben ser revelados a nadie.<\\/p><p>ELMSTON nunca le pedir\\u00e1 ni le dirigir\\u00e1 a un sitio web que le pida estos datos. Por favor, visite nuestra p\\u00e1gina de seguridad aqu\\u00ed para obtener m\\u00e1s informaci\\u00f3n.<\\/p><p><br><\\/p><p><\\/p><p>Gracias por elegir ELMSTON\\ud83d\\udc9c.<\\/p><p style=\\"text-align: center; \\"><\\/p><p style=\\"text-align: center; \\"><\\/p><p style=\\"text-align: center; \\"><span style=\\"font-size: 1rem;\\"><br><\\/span><\\/p><p style=\\"text-align: center; \\"><span style=\\"font-size: 1rem;\\"><br><\\/span><\\/p><p style=\\"text-align: center; \\"><span style=\\"font-size: 1rem;\\">Copyright \\u00a9 2022. Elmston Group Inc. All rights reserved<\\/span><br><\\/p>"',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'mail.privateemail.com',
    'smtp_port' => '465',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'help@elmston.co',
    'smtp_password' => 'Skybee001.',
  ),
  'push_notification' => 1,
  'min_transfer' => '0',
  'max_transfer' => '0',
  'transfer_charge' => '0',
  'bonus_amount' => '20',
  'joining_bonus' => 0,
  'error_log' => 0,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 0,
  'tawk_id' => '62d7e2fcb0d10b6f3e7d4766',
  'tawk_status' => 1,
  'fb_messenger_status' => 0,
  'fb_app_id' => '1983831301869331',
  'fb_page_id' => '1983831301869331',
  'reCaptcha_status_login' => 0,
  'reCaptcha_status_registration' => 0,
  'MEASUREMENT_ID' => 'G-TFQZ8YZ468',
  'analytic_status' => 0,
);